runtime: go
api_version: go1.9

handlers:
- url: /.*
  script: _go_app

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_pending_latency: 2000ms

skip_files:
- app.yaml
- webapp/node_modules/(.*/)?
- webapp/public
- webapp/src
- webapp/images.d.ts
- webapp/package.json
- webapp/README.md
- webapp/tsconfig.json
- webapp/tsconfig.prod.json
- webapp/tsconfig.test.json
- webapp/tslint.json
- webapp/yarn.lock
