name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn typecheck

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn eslint

  prettier-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn prettier-check

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build

