name: typecheck
'on': pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn typecheck

